name: .NET

on:
  #push:
  #   branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
          name: .net-app
          path: /home/runner/work/verademo-sample/verademo-sample/bin/Debug/net6.0/verademo-sample.dll
          
    - name: GitHub Script
      run: echo $GITHUB_ACTION_PATH
      
  security_analysis:
    runs-on: windows-latest
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: .net-app
          # Destination path
          path:  ${{env.DOTNET_ROOT}}/myapp
          
      - name: GitHub Script
        uses: actions/github-script@v6.1.0
        with:
          # The script to run
          script: 
            dir
          # The GitHub token used to create an authenticated client
          #github-token: # optional, default is ${{ github.token }}
          # Whether to tell the GitHub client to log details of its requests
          #debug: # optional
          # An optional user-agent string
          #user-agent: # optional, default is actions/github-script
          # A comma-separated list of API previews to accept
          #previews: # optional
          # Either "string" or "json" (default "json")—how the result will be encoded
          #result-encoding: # optional, default is json
 

