name: .NET

on:
  #push:
  #   branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Envionmental Info
      run: env
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: GitHub Script
      run: echo ${GITHUB_WORKSPACE}
      
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: GitHub Script
      run: echo ${GITHUB_WORKSPACE}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build Produced
      run: ls -la ${{github.workspace}}/bin/Debug/net6.0/
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
          name: .net-app
          path: ${{github.workspace}}/bin/Debug/net6.0/
      
  security_analysis:
    runs-on: windows-latest
    
    steps:
      - name: GitHub Script
        run: echo ${GITHUB_ACTION_PATH}
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: .net-app
          # Destination path
          path:  ${GITHUB_WORKSPACE}
          
      - name: GitHub Script
        run: ls -la
 

