name: Manual Build and Test Application

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Envionmental Info
        run: env

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        
        with:
          dotnet-version: 6.0.x

      - name: GitHub Script
        run: echo ${GITHUB_WORKSPACE}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: GitHub Script
        run: echo ${GITHUB_WORKSPACE}

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Produced
        run: ls -la ${{github.workspace}}/bin/Debug/net6.0/

      - name: Compress Content
        #run: tar -czvf application.tar.gz --exclude=*.json ${{github.workspace}}/bin/Debug/net6.0/*.*
        run: |
          cd ${{github.workspace}}/bin/Debug/net6.0
          zip -r ${{github.workspace}}/application.zip . -x *.json

      - name: Verify Content
        run: echo ${GITHUB_WORKSPACE} | ls -la

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
            name: .net-app
            path: ${{github.workspace}}/application.zip
          
  sast_analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Prepare environment   
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '11'
          distribution: 'microsoft'

      - name: Verify Java
        run: 'java --version'
   
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: .net-app
          # Destination path
          path: ${{github.workspace}}
          
      - name: Confirm Contents
        run: ls -la
      
      - name: Veracode Upload And Scan
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-uploadandscan-action@35794dab9fbcd28fac19e44963f80646b27f4a7f
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          # appname
          appname: ${{ github.repository }}
          # createprofile
          createprofile: true
          # filepath
          #filepath: 
          # version
          version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          # vid
          vid: ${{secrets.VERACODE_API_ID}}
          # vkey
          vkey: ${{secrets.VERACODE_API_KEY}}
          # true or false
          createsandbox: true
          # name of the sandbox
          sandboxname: 'Release Candidate'
          # wait X minutes for the scan to complete
          #scantimeout: # optional
          # modules to exclude from module selection
          #exclude: # optional
          # modules to include in module selection
          #include: # optional
          # business criticality - policy selection
          #criticality: # optional
          # filename pattern
          pattern: '*.zip'
          # replacement
          #replacement: # optional
          # specify to scan in a sandbox
          #sandboxid: # optional
          # All top level modules
          #scanallnonfataltoplevelmodules: # optional
          # platform selected modules
          #selected: # optional
          # selected modules like from previous scan
          #selectedpreviously: # optional
          # teams
          #teams: # optional
          # teams
          #toplevel: # optional
          # automatically delete the current scan if there are any errors when uploading files or starting the scan
          #deleteincompletescan: # optional
          # specify version of the Java API Wrapper; default is latest
          #javawrapperversion: # optional
          # show detailed diagnostic information, which you can use for debugging, in the output.
          #debug: # optional



    
    
    
    
    
 
