name: reusable workflow caller

on:
  workflow_dispatch:
  
jobs: 
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      username: mona
    secrets:
      veracode-api-id: ${{ secrets.veracode-api-id }}
