name: Verademo Sample Reusable Workflow

on:
  workflow_dispatch:
  
jobs: 
  call-build-workflow:
    uses: dmedeiros-veracode/verademo-sample/.github/workflows/verademo-sample-reusable-dotnet-build-linux-workflow.yml@master
