name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      veracode-api-id:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - id: step 1
        run: echo ${{ inputs.username }}
      - id: step 2
        run: echo ${{ secrets.veracode-api-id }}
